version: "3.8"

services:
  app:
    build:
      context: ./main
      dockerfile: Dockerfile-dev
    ports:      
      - '3000:3000'
    volumes:
      - ./main:/app
    depends_on: 
      - db        
      - redis
    # command: ["./await_db.sh"]
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
      - DB_DATABASE=database    

  ms:
    build:
      context: ./ms
      dockerfile: Dockerfile-dev
    ports:      
      - '3001:3000'
    volumes:
      - ./ms:/app
    depends_on: 
      - app            
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
      - DB_DATABASE=database   
  

  db:
    image: mysql:5.6
    ports:
      - '3306:3306'
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      
  redis:
    image: redis:5.0.5-alpine
    ports:
      - '6379:6379'
    volumes:
      - ./volumes/redis:/data

      